version: '2'
services:
  lighthouse-reporter:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lighthouse-reporter
    env_file:
      - .env
    ports:
      - '3333:3333'
    networks:
      - lighthouse-network

networks:
  lighthouse-network:
    driver: bridge