version: '2'
services:
  lighthouse-reporter:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lighthouse-reporter
    env_file:
      - .env
    networks:
      - network
    ports:
      - '3333:3333'
networks:
  network:
    driver: bridge